### ISSUE TITLE
Integration into VisiCut

### ISSUE THREAD

**Issue by t-oster** [dimsumlabs/k40_whisperer#1]
Hi,

I am the maintainer of VisiCut (https://github.com/t-oster/VisiCut), an application similar to k40 whisperer, which already supports many lasercutters. Maybe we should work together and integrate a k40 driver into VisiCut so we do not need to implement all features in both projects.
However you seem to like python and I am more a Java guy, so this might not be straitforward. However adding a driver to VisiCut is as simple as https://github.com/t-oster/VisiCut/wiki/Developing-a-new-Lasercutter-Driver.
Please tell me what you think. I have already users asking for K40 support (https://github.com/t-oster/LibLaserCut/issues/81)

**Comment by hamishcoleman** [comment]
Hey there,
Firstly, we are not the original source of the K40 whisperer software - look at http://www.scorchworks.com/K40whisperer/k40whisperer.html for that.  Unfortunately, he does not appear to be interested in many modern development techniques, like version control :-(

The python unit tests that I wrote cover the hardware interface parts of this software - so hopefully there is some information in them to show how to talk to the USB device and the custom protocol the cutter uses.  Its not derived from any of the standard protocols unfortunately.

Hopefully some of that has been helpful to you - as you noticed, I'm not much of a Java guy, but - more importantly - I am somewhat time-poor, so I probably cannot help much on any code.

**Comment by t-oster** [comment]
Hi,
thank you for your answer. I am also very short on time, but maybe there are some volunteers in the VisiCut community, who are willing to port the driver. I will contact the author of K40 whispere in order to get his opinion. Thank you for your quick answer.

**Comment by dlarue** [comment]
I 2nd the idea of porting what Scorchworks has done with the K40 controller and getting it working with VisiCut.  I am currently using K40 Whisperer because I don't yet have my smoothieware compatible board yet. I will be using Visicut over the network once all the hardware is shifted.

**Comment by t-oster** [comment]
We will have K40 support in VisiCut soon, so this can be considered closed
